[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "localhost:8080"]
env = [
  "PHPRC=/app/config/php.ini",
  "APP_ENV=production",
  "APP_DEBUG=false",
  "PHP_CLI_SERVER_WORKERS=4"
]
